apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 25
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/cartservice:v0.3.1
        ports:
        - containerPort: 7070
        env:
        - name: REDIS_ADDR
          value: "redis-cart:6379"
        resources:
          requests:
            cpu: 150m
            memory: 84Mi
          limits:
            cpu: 200m
            memory: 120Mi
        readinessProbe:
          initialDelaySeconds: 45
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=35s"]
        livenessProbe:
          initialDelaySeconds: 55
          periodSeconds: 30
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=35s"]
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
  - name: grpc
    port: 7070
    targetPort: 7070